# Chargement du CSV

### Imports

In [15]:
import pandas as pd
import numpy as np

### Chargement du CSV

In [18]:
data = pd.read_csv("../../raw_data/recipes_ingredients.csv")
data.set_index(keys="id", inplace=True)
data.head()

,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags
id,,,,,,,,
71247,Cherry Streusel Cobbler,"I haven't made this in years, so I'm just gues...","[""cherry pie filling"", ""condensed milk"", ""melt...","[""2 (21 ounce) cans cherry pie filling"",""2...","[""Preheat oven to 375°F."", ""Spread cherry pie ...",6.0,1 (347 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
76133,Reuben and Swiss Casserole Bake,I think this is even better than a reuben sand...,"[""corned beef chopped"", ""sauerkraut cold water...","[""1/2-1 lb corned beef, cooked and choppe...","[""Set oven to 350 degrees F."", ""Butter a 9 x 1...",4.0,1 (207 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
503816,Yam-Pecan Recipe,A lady I work with heard me taking about ZWT a...,"[""unsalted butter"", ""vegetable oil"", ""all - pu...","[""3/4 cup unsalted butter, at room tempera...","[""Preheat oven to 350°F In a mixing bowl, usi...",8.0,1 (198 g),"[""time-to-make"", ""course"", ""main-ingredient"", ..."
418749,Tropical Orange Layer Cake,An easy and delicious cake. Great for a summ...,"[""orange cake mix"", ""instant vanilla pudding"",...","[""1 (18 ounce) pkge.orange cake mix"",""1 (3...","[""In a large mixing bowl, combine the first 6 ...",16.0,1 (191 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
392934,Safe to Eat Raw Chocolate Chip Oreo Cookie &qu...,I was searching the web for something like thi...,"[""butter"", ""brown sugar"", ""granulated sugar"", ...","[""1/2 cup butter, room temperature "",""1/2 ...","[""Cream butter and sugars together."", ""Blend i...",24.0,1 (26 g),"[""15-minutes-or-less"", ""time-to-make"", ""course..."

In [23]:
import ast

errors = []

def safe_literal_eval(value):
    try:
     return ast.literal_eval(value)
    except (ValueError, SyntaxError) as e:
        errors.append((value, str(e)))
    return value

data["ingredients"] = data["ingredients"].apply(safe_literal_eval)

In [25]:
mot = "chicken"
data_filtre = data[data['ingredients'].apply(lambda x: any(mot in ing.lower() for ing in x))]
data_filtre

,name,description,ingredients,ingredients_raw,steps,servings,serving_size,tags
id,,,,,,,,
532245,Chicken and Petite Carrots,I made this for dinner since I had nothing to ...,"[chicken breasts cutlets, petite carrots, vege...","[""2 chicken breasts, cutlets "",""1 (2 l...","[""Step 1: Pull out a cutting board and cut the...",4.0,1 (443 g),"[""time-to-make"", ""preparation"", ""presentation""..."
437096,Junior League- Fiesta Chicken Salad W/ Lime Ci...,Fiesta Chicken Salad and Lime Cilantro Vinaigr...,"[chopped shallot, fresh lime juice, chopped fr...","[""1/2 cup chopped shallot"",""1/4 cup fre...","[""For the vinaigrette, combine the shallots, l...",6.0,1 (212 g),"[""weeknight"", ""30-minutes-or-less"", ""time-to-m..."
187408,"Aloo Gobi Mattar - Cauliflower, Pea and Potato...",Why choose between aloo gobi and aloo mattar w...,"[cauliflower, large onions, baking potatoes, f...","[""1 large cauliflower, cut into small flo...","[""Heat oil in a large wok, karahi, or deep non...",6.0,1 (342 g),"[""lactose"", ""60-minutes-or-less"", ""time-to-mak..."
164054,Spanish Style Chicken (Grilled With Raisin Win...,I am looking to thin my collection of cookbook...,"[olive oil, white onion, mushroom, all, dry wh...","[""1 1/2 tablespoons olive oil"",""1 large ...","[""Heat oil in a medium saucepan. Add onions a...",4.0,1 (333 g),"[""lactose"", ""60-minutes-or-less"", ""time-to-mak..."
21702,Caramelized Onion Chicken,This recipe was adapted from Cooking Light. On...,"[boneless skinless chicken breasts, salt peppe...","[""2 boneless skinless chicken breasts, c...","[""Sprinkle the chicken with salt and pepper."",...",4.0,1 (122 g),"[""30-minutes-or-less"", ""time-to-make"", ""course..."
...,...,...,...,...,...,...,...,...
12526,Baked Sesame Chicken,"These are easy, moist and delicious!!","[chicken breasts skin bone, sesame oil, sherry...","[""8 chicken breasts, no skin,no bone,r-t...","[""If using plain Saltine crackers, add 2 tsp.""...",4.0,1 (363 g),"[""60-minutes-or-less"", ""time-to-make"", ""main-i..."
267020,Ben's Habanero Chicken,"This is something my DH came up with, this stu...","[chicken breasts, margarine, red pepper, whole...","[""1 1/2 cups water"",""3 chicken breas...","[""Add chicken breasts to pan and sliced habane...",2.0,1 (449 g),"[""60-minutes-or-less"", ""time-to-make"", ""course..."
444042,Toasted Barley With Mixed Vegetables,I got this from the eat better America website...,"[uncooked hulled barley, chicken broth, large ...","[""1/2 cup uncooked hulled barley"",""1 (14 ...","[""Spray a 12 skillet with cooking spray. Cook ...",4.0,1 (290 g),"[""weeknight"", ""time-to-make"", ""course"", ""main-..."
357821,Chicken Pesto Pizza,Found in a cookbook and putting here for safe ...,"[frozen bread dough, chicken tenders, red onio...","[""1 loaf frozen bread dough, thawed "",""8 ...","[""Preheat oven to 375* F."", ""Sprinkle baking s...",1.0,1 (406 g),"[""time-to-make"", ""course"", ""main-ingredient"", ..."
510848,Chicken and Dumplings &ndash; Crock Pot,Fix it and Forget it Lightly – Slow Cooker rec...,"[chicken cubed, frozen vegetables, onion, chic...","[""1 lb chicken, cubed "",""1 lb frozen...","[""Combine chicken, vegetables, onion and chick...",6.0,1 (323 g),"[""course"", ""preparation"", ""5-ingredients-or-le..."